# Generated by Django 2.2 on 2019-04-24 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_auto_20190424_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='Availability',
            field=models.DurationField(),
        ),
    ]
