# Generated by Django 2.2 on 2019-04-24 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_auto_20190424_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='Availability',
            field=models.TimeField(),
        ),
    ]
