# Generated by Django 2.2 on 2019-04-24 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0007_auto_20190424_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AvailableDate', models.DateField()),
                ('AvailableTime', models.TimeField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.Doctor')),
            ],
        ),
    ]
