# Generated by Django 2.2 on 2019-04-24 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0008_avail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='Availability',
        ),
    ]
