# Generated by Django 2.2 on 2019-04-24 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0009_remove_doctor_availability'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avail',
        ),
    ]
