# Generated by Django 2.2 on 2019-04-24 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0011_availability'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Availability',
        ),
    ]
